"""Test data for knowledge system validation.

Auto-generated from DOC.md files in /app/context-hub/dist/.
Each entry maps a search query to expected results.
"""

# PowerShell cmdlets: query → expected package prefix
# Total available: 231, testing top 100
PS_CMDLETS = {
    "Add-Content": "microsoft/pwsh-crossplatform",
    "Add-Member": "microsoft/pwsh-objects",
    "Compare-Object": "microsoft/pwsh-objects",
    "Connect-PSSession": "microsoft/pwsh-remoting",
    "Connect-Widget": "microsoft/pwsh-modules",
    "ConvertFrom-Json": "microsoft/pwsh-api-web",
    "ConvertFrom-StringData": "microsoft/pwsh-cim-wmi",
    "ConvertTo-Csv": "microsoft/pwsh-files-data",
    "ConvertTo-Json": "microsoft/pwsh-api-web",
    "ConvertTo-SecureString": "microsoft/pwsh-api-web",
    "ConvertTo-Upper": "microsoft/pwsh-functions",
    "Copy-Item": "microsoft/pwsh-testing",
    "Debug-Job": "microsoft/pwsh-debugging",
    "Debug-Runspace": "microsoft/pwsh-debugging",
    # Deploy-App and Deploy-Service are example names in docs, not real cmdlets
    "Disable-PSBreakpoint": "microsoft/pwsh-debugging",
    "Disable-ScheduledTask": "microsoft/pwsh-windows-admin",
    "Disconnect-PSSession": "microsoft/pwsh-remoting",
    "Enable-PSBreakpoint": "microsoft/pwsh-debugging",
    "Enable-PSRemoting": "microsoft/pwsh-remoting",
    "Enable-ScheduledTask": "microsoft/pwsh-windows-admin",
    "Enable-WindowsOptionalFeature": "microsoft/pwsh-windows-admin",
    "Enter-PSHostProcess": "microsoft/pwsh-debugging",
    "Enter-PSSession": "microsoft/pwsh-debugging",
    "Exit-PSSession": "microsoft/pwsh-remoting",
    "Export-Clixml": "microsoft/pwsh-files-data",
    "Export-Csv": "microsoft/pwsh-files-data",
    "Export-ModuleMember": "microsoft/pwsh-modules",
    "Find-Command": "microsoft/pwsh-psresourceget",
    "Find-DscResource": "microsoft/pwsh-psresourceget",
    "Find-Module": "microsoft/pwsh-modules",
    "Find-PSResource": "microsoft/pwsh-modules",
    "Find-Script": "microsoft/pwsh-psresourceget",
    "ForEach-Object": "microsoft/pwsh-api-web",
    "Format-Table": "microsoft/pwsh-remoting",
    "Get-AzContext": "microsoft/pwsh-modules",
    "Get-BThing": "microsoft/pwsh-psresourceget",
    "Get-ChildItem": "microsoft/pwsh-collections",
    "Get-CimAssociatedInstance": "microsoft/pwsh-cim-wmi",
    "Get-CimClass": "microsoft/pwsh-cim-wmi",
    "Get-CimInstance": "microsoft/pwsh-cim-wmi",
    "Get-Clipboard": "microsoft/pwsh-crossplatform",
    "Get-Command": "microsoft/pwsh-core",
    "Get-Config": "microsoft/pwsh-debugging",
    "Get-Content": "microsoft/pwsh-cim-wmi",
    "Get-Credential": "microsoft/pwsh-cim-wmi",
    "Get-Data": "microsoft/pwsh-debugging",
    "Get-Date": "microsoft/pwsh-classes",
    "Get-DefaultConfig": "microsoft/pwsh-core",
    "Get-DnsClientServerAddress": "microsoft/pwsh-windows-admin",
    "Get-EventLog": "microsoft/pwsh-windows-admin",
    "Get-ExecutionPolicy": "microsoft/pwsh-script-patterns",
    "Get-FileHash": "microsoft/pwsh-files-data",
    "Get-GPO": "microsoft/pwsh-crossplatform",
    "Get-Greeting": "microsoft/pwsh-pipeline",
    "Get-InstalledModule": "microsoft/pwsh-psresourceget",
    "Get-InstalledPSResource": "microsoft/pwsh-psresourceget",
    "Get-InstalledScript": "microsoft/pwsh-psresourceget",
    "Get-InternalHelper": "microsoft/pwsh-testing",
    "Get-Item": "microsoft/pwsh-api-web",
    "Get-ItemProperty": "microsoft/pwsh-cim-wmi",
    "Get-Job": "microsoft/pwsh-jobs-async",
    "Get-Member": "microsoft/pwsh-classes",
    "Get-Module": "microsoft/pwsh-modules",
    "Get-Msg": "microsoft/pwsh-strings",
    "Get-Name": "microsoft/pwsh-script-patterns",
    "Get-NetAdapter": "microsoft/pwsh-windows-admin",
    "Get-NetFirewallProfile": "microsoft/pwsh-windows-admin",
    "Get-NetFirewallRule": "microsoft/pwsh-windows-admin",
    "Get-NetIPAddress": "microsoft/pwsh-windows-admin",
    "Get-NetRoute": "microsoft/pwsh-windows-admin",
    "Get-Numbers": "microsoft/pwsh-pipeline",
    "Get-PSBreakpoint": "microsoft/pwsh-debugging",
    "Get-PSRepository": "microsoft/pwsh-psresourceget",
    "Get-PSResourceRepository": "microsoft/pwsh-psresourceget",
    "Get-PSSession": "microsoft/pwsh-remoting",
    "Get-PfxCertificate": "microsoft/pwsh-api-web",
    "Get-Process": "microsoft/pwsh-collections",
    "Get-Random": "microsoft/pwsh-jobs-async",
    "Get-RemoteInfo": "microsoft/pwsh-cim-wmi",
    "Get-RemoteMailbox": "microsoft/pwsh-remoting",
    "Get-Runspace": "microsoft/pwsh-debugging",
    "Get-ScheduledTask": "microsoft/pwsh-crossplatform",
    "Get-ScheduledTaskInfo": "microsoft/pwsh-windows-admin",
    "Get-ServerInfo": "microsoft/pwsh-functions",
    "Get-Service": "microsoft/pwsh-crossplatform",
    "Get-Thing": "microsoft/pwsh-functions",
    "Get-TraceSource": "microsoft/pwsh-debugging",
    "Get-Uptime": "microsoft/pwsh-jobs-async",
    "Get-User": "microsoft/pwsh-functions",
    "Get-Widget": "microsoft/pwsh-modules",
    "Get-WidgetConnections": "microsoft/pwsh-modules",
    "Get-WinEvent": "microsoft/pwsh-crossplatform",
    "Get-WindowsFeature": "microsoft/pwsh-windows-admin",
    "Get-WindowsOptionalFeature": "microsoft/pwsh-windows-admin",
    "Get-WmiObject": "microsoft/pwsh-cim-wmi",
    "Group-Object": "microsoft/pwsh-collections",
    "Import-Clixml": "microsoft/pwsh-files-data",
    "Import-Csv": "microsoft/pwsh-files-data",
}

# Python packages: search query → package ID
# Keys must be unique (Python dicts silently drop duplicates)
PY_PACKAGES = {
    "database": "airtable/database",
    "analytics": "amplitude/analytics",
    "providers-atlassian-jira": "apache-airflow/providers-atlassian-jira",
    "providers-weaviate": "apache-airflow/providers-weaviate",
    "confluence": "atlassian/confluence",
    "auth0 identity": "auth0/identity",
    "s3": "aws/s3",
    "ai-formrecognizer": "azure/ai-formrecognizer",
    "cognitiveservices-speech": "azure/cognitiveservices-speech",
    "common": "azure/common",
    "core": "azure/core",
    "azure identity": "azure/identity",
    "mgmt-cdn": "azure/mgmt-cdn",
    "mgmt-cognitiveservices": "azure/mgmt-cognitiveservices",
    "mgmt-containerinstance": "azure/mgmt-containerinstance",
    "mgmt-devtestlabs": "azure/mgmt-devtestlabs",
    "mgmt-eventgrid": "azure/mgmt-eventgrid",
    "mgmt-frontdoor": "azure/mgmt-frontdoor",
    "mgmt-hdinsight": "azure/mgmt-hdinsight",
    "mgmt-loganalytics": "azure/mgmt-loganalytics",
    "mgmt-logic": "azure/mgmt-logic",
    "mgmt-machinelearningservices": "azure/mgmt-machinelearningservices",
    "mgmt-managedservices": "azure/mgmt-managedservices",
    "mgmt-netapp": "azure/mgmt-netapp",
    "mgmt-network": "azure/mgmt-network",
    "mgmt-policyinsights": "azure/mgmt-policyinsights",
    "mgmt-redis": "azure/mgmt-redis",
    "mgmt-resource-policy": "azure/mgmt-resource-policy",
    "mgmt-servicebus": "azure/mgmt-servicebus",
    "mgmt-signalr": "azure/mgmt-signalr",
    "mgmt-trafficmanager": "azure/mgmt-trafficmanager",
    "mgmt-web": "azure/mgmt-web",
    "azure-search-documents": "azure/search-documents",
    "storage-file-datalake": "azure/storage-file-datalake",
    "trading": "binance/trading",
    "gateway": "braintree/gateway",
    "embeddings-db": "chromadb/embeddings-db",
    "workers": "cloudflare/workers",
    "monitoring": "datadog/monitoring",
    "datahub sdk": "datahub/sdk",
    "deepgram speech": "deepgram/speech",
    "translation": "deepl/translation",
    "headless-cms": "directus/headless-cms",
    "bot": "discord/bot",
    "compressor": "django/compressor",
    "countries": "django/countries",
    "text-to-speech": "elevenlabs/text-to-speech",
    "fastapi-users": "fastapi-users/package",
    "dance": "flask/dance",
    "smorest": "flask/smorest",
    "genai": "gemini/genai",
    "api-gateway": "google/api-gateway",
    "beyondcorp-appconnections": "google/beyondcorp-appconnections",
    "bigquery-datatransfer": "google/bigquery-datatransfer",
    "config-connector": "google/config-connector",
    "deploy": "google/deploy",
    "gke-hub": "google/gke-hub",
    "gke-multicloud": "google/gke-multicloud",
    "managed-identities": "google/managed-identities",
    "network-management": "google/network-management",
    "optimization": "google/optimization",
    "orchestration-airflow": "google/orchestration-airflow",
    "private-ca": "google/private-ca",
    "redis": "google/redis",
    "retail": "google/retail",
    "google speech": "google/speech",
    "tpu": "google/tpu",
    "grpcio": "grpcio/package",
    "httpcore": "httpcore/package",
    "hubspot crm": "hubspot/crm",
    "messaging": "intercom/messaging",
    "issues": "jira/issues",
    "streaming": "kafka/streaming",
    "ade": "landingai/ade",
    "observability": "langfuse/observability",
    "feature-flags": "launchdarkly/feature-flags",
    "litestar": "litestar/package",
    "msal": "msal/package",
    "workspace-api": "notion/workspace-api",
    "okta identity": "okta/identity",
    "chat": "openai/chat",
    "pinecone sdk": "pinecone/sdk",
    "banking": "plaid/banking",
    "orm": "prisma/orm",
    "prometheus-client": "prometheus-client/package",
    "vector-search": "qdrant/vector-search",
    "message-queue": "rabbitmq/message-queue",
    "razorpay payments": "razorpay/payments",
    "key-value": "redis/key-value",
    "rq": "rq/package",
    "salesforce crm": "salesforce/crm",
    "email-api": "sendgrid/email-api",
    "error-tracking": "sentry/error-tracking",
    "sqlalchemy": "sqlalchemy/package",
    "square payments": "square/payments",
    "auth": "stytch/auth",
    "tavily sdk": "tavily/sdk",
    "weaviate-client": "weaviate-client/package",
    "vector-db": "weaviate/vector-db",
    "support": "zendesk/support",
}

# Nutanix SDK modules: module name → package ID
# Total: 13
NUTANIX_MODULES = {
    "nutanix-aiops": "nutanix/nutanix-aiops",
    "nutanix-clustermgmt": "nutanix/nutanix-clustermgmt",
    "nutanix-datapolicies": "nutanix/nutanix-datapolicies",
    "nutanix-dataprotection": "nutanix/nutanix-dataprotection",
    "nutanix-licensing": "nutanix/nutanix-licensing",
    "nutanix-lifecycle": "nutanix/nutanix-lifecycle",
    "nutanix-microseg": "nutanix/nutanix-microseg",
    "nutanix-monitoring": "nutanix/nutanix-monitoring",
    "nutanix-networking": "nutanix/nutanix-networking",
    "nutanix-prism": "nutanix/nutanix-prism",
    "nutanix-sdk": "nutanix/nutanix-sdk",
    "nutanix-vmm": "nutanix/nutanix-vmm",
    "nutanix-volumes": "nutanix/nutanix-volumes",
}

# Bash/DevOps tools (manual list)
BASH_TOOLS = {
    "ansible": "ansible/package",
    "docker": "docker/package",
    "docker compose": "docker/package",
    "git": "pre-commit/package",
    "redis": "redis/key-value",
}

