"""Test data for knowledge system validation.

Auto-generated from DOC.md files in /app/context-hub/dist/.
Each entry maps a search query to expected results.
"""

# PowerShell cmdlets: query → expected package prefix
# Total available: 231, testing top 100

PS_CMDLETS = {
    "Add-AssertionOperator": "microsoft/pwsh-pester",
    "Add-Content": "microsoft/pwsh-management",
    "Add-History": "microsoft/pwsh-core-cmdlets",
    "Add-Member": "microsoft/pwsh-utility",
    "Add-ShouldOperator": "microsoft/pwsh-pester",
    "Add-Type": "microsoft/pwsh-utility",
    "Assert-MockCalled": "microsoft/pwsh-pester",
    "Assert-VerifiableMock": "microsoft/pwsh-pester",
    "Clear-Content": "microsoft/pwsh-management",
    "Clear-History": "microsoft/pwsh-core-cmdlets",
    "Clear-Item": "microsoft/pwsh-management",
    "Clear-ItemProperty": "microsoft/pwsh-management",
    "Clear-Variable": "microsoft/pwsh-utility",
    "Compare-Object": "microsoft/pwsh-utility",
    "Compress-Archive": "microsoft/pwsh-archive",
    "Compress-PSResource": "microsoft/pwsh-psresourceget-cmdlets",
    "Convert-Path": "microsoft/pwsh-management",
    "ConvertFrom-CliXml": "microsoft/pwsh-utility",
    "ConvertFrom-Csv": "microsoft/pwsh-utility",
    "ConvertFrom-Json": "microsoft/pwsh-utility",
    "ConvertFrom-Markdown": "microsoft/pwsh-utility",
    "ConvertFrom-SecureString": "microsoft/pwsh-security",
    "ConvertFrom-StringData": "microsoft/pwsh-utility",
    "ConvertTo-CliXml": "microsoft/pwsh-utility",
    "ConvertTo-JUnitReport": "microsoft/pwsh-pester",
    "ConvertTo-NUnitReport": "microsoft/pwsh-pester",
    "ConvertTo-Pester4Result": "microsoft/pwsh-pester",
    "ConvertTo-SecureString": "microsoft/pwsh-security",
    "Copy-Item": "microsoft/pwsh-management",
    "Copy-ItemProperty": "microsoft/pwsh-management",
    "Debug-Job": "microsoft/pwsh-core-cmdlets",
    "Debug-Process": "microsoft/pwsh-management",
    "Disable-ExperimentalFeature": "microsoft/pwsh-core-cmdlets",
    "Enable-ExperimentalFeature": "microsoft/pwsh-core-cmdlets",
    "Enter-PSHostProcess": "microsoft/pwsh-core-cmdlets",
    "Enter-PSSession": "microsoft/pwsh-core-cmdlets",
    "Exit-PSHostProcess": "microsoft/pwsh-core-cmdlets",
    "Exit-PSSession": "microsoft/pwsh-core-cmdlets",
    "Expand-Archive": "microsoft/pwsh-archive",
    "Export-JUnitReport": "microsoft/pwsh-pester",
    "Export-ModuleMember": "microsoft/pwsh-core-cmdlets",
    "Export-NUnitReport": "microsoft/pwsh-pester",
    "Find-Command": "microsoft/pwsh-powershellget",
    "Find-DscResource": "microsoft/pwsh-powershellget",
    "Find-Module": "microsoft/pwsh-powershellget",
    "Find-PSResource": "microsoft/pwsh-psresourceget-cmdlets",
    "Find-Package": "microsoft/pwsh-packagemgmt",
    "Find-PackageProvider": "microsoft/pwsh-packagemgmt",
    "Find-RoleCapability": "microsoft/pwsh-powershellget",
    "Find-Script": "microsoft/pwsh-powershellget",
    "Get-AssertionOperator": "microsoft/pwsh-pester",
    "Get-ChildItem": "microsoft/pwsh-management",
    "Get-Clipboard": "microsoft/pwsh-management",
    "Get-CmsMessage": "microsoft/pwsh-security",
    "Get-Credential": "microsoft/pwsh-security",
    "Get-CredsFromCredentialProvider": "microsoft/pwsh-powershellget",
    "Get-ExecutionPolicy": "microsoft/pwsh-security",
    "Get-InstalledModule": "microsoft/pwsh-powershellget",
    "Get-InstalledPSResource": "microsoft/pwsh-psresourceget-cmdlets",
    "Get-InstalledScript": "microsoft/pwsh-powershellget",
    "Get-PSReadLineKeyHandler": "microsoft/pwsh-psreadline",
    "Get-PSReadLineOption": "microsoft/pwsh-psreadline",
    "Get-PSRepository": "microsoft/pwsh-powershellget",
    "Get-PSResource": "microsoft/pwsh-psresourceget-cmdlets",
    "Get-PSResourceRepository": "microsoft/pwsh-psresourceget-cmdlets",
    "Get-PSScriptFileInfo": "microsoft/pwsh-psresourceget-cmdlets",
    "Get-Package": "microsoft/pwsh-packagemgmt",
    "Get-PackageProvider": "microsoft/pwsh-packagemgmt",
    "Get-PackageSource": "microsoft/pwsh-packagemgmt",
    "Get-PfxCertificate": "microsoft/pwsh-security",
    "Import-PSGetRepository": "microsoft/pwsh-psresourceget-cmdlets",
    "Import-PackageProvider": "microsoft/pwsh-packagemgmt",
    "Install-Module": "microsoft/pwsh-powershellget",
    "Install-PSResource": "microsoft/pwsh-psresourceget-cmdlets",
    "Install-Package": "microsoft/pwsh-packagemgmt",
    "Install-PackageProvider": "microsoft/pwsh-packagemgmt",
    "New-PSScriptFileInfo": "microsoft/pwsh-psresourceget-cmdlets",
    "Protect-CmsMessage": "microsoft/pwsh-security",
    "Publish-PSResource": "microsoft/pwsh-psresourceget-cmdlets",
    "Register-PackageSource": "microsoft/pwsh-packagemgmt",
    "Remove-PSReadLineKeyHandler": "microsoft/pwsh-psreadline",
    "Save-Package": "microsoft/pwsh-packagemgmt",
    "Set-ExecutionPolicy": "microsoft/pwsh-security",
    "Set-PSReadLineKeyHandler": "microsoft/pwsh-psreadline",
    "Set-PSReadLineOption": "microsoft/pwsh-psreadline",
    "Start-ThreadJob": "microsoft/pwsh-threadjob",
    "Start-Transcript": "microsoft/pwsh-host",
    "Stop-Transcript": "microsoft/pwsh-host",
    "Unprotect-CmsMessage": "microsoft/pwsh-security",
}

# Python packages: search query → package ID
# Keys must be unique (Python dicts silently drop duplicates)
PY_PACKAGES = {
    "database": "airtable/database",
    "analytics": "amplitude/analytics",
    "providers-atlassian-jira": "apache-airflow/providers-atlassian-jira",
    "providers-weaviate": "apache-airflow/providers-weaviate",
    "confluence": "atlassian/confluence",
    "auth0 identity": "auth0/identity",
    "s3": "aws/s3",
    "ai-formrecognizer": "azure/ai-formrecognizer",
    "cognitiveservices-speech": "azure/cognitiveservices-speech",
    "common": "azure/common",
    "core": "azure/core",
    "azure identity": "azure/identity",
    "mgmt-cdn": "azure/mgmt-cdn",
    "mgmt-cognitiveservices": "azure/mgmt-cognitiveservices",
    "mgmt-containerinstance": "azure/mgmt-containerinstance",
    "mgmt-devtestlabs": "azure/mgmt-devtestlabs",
    "mgmt-eventgrid": "azure/mgmt-eventgrid",
    "mgmt-frontdoor": "azure/mgmt-frontdoor",
    "mgmt-hdinsight": "azure/mgmt-hdinsight",
    "mgmt-loganalytics": "azure/mgmt-loganalytics",
    "mgmt-logic": "azure/mgmt-logic",
    "mgmt-machinelearningservices": "azure/mgmt-machinelearningservices",
    "mgmt-managedservices": "azure/mgmt-managedservices",
    "mgmt-netapp": "azure/mgmt-netapp",
    "mgmt-network": "azure/mgmt-network",
    "mgmt-policyinsights": "azure/mgmt-policyinsights",
    "mgmt-redis": "azure/mgmt-redis",
    "mgmt-resource-policy": "azure/mgmt-resource-policy",
    "mgmt-servicebus": "azure/mgmt-servicebus",
    "mgmt-signalr": "azure/mgmt-signalr",
    "mgmt-trafficmanager": "azure/mgmt-trafficmanager",
    "mgmt-web": "azure/mgmt-web",
    "azure-search-documents": "azure/search-documents",
    "storage-file-datalake": "azure/storage-file-datalake",
    "trading": "binance/trading",
    "gateway": "braintree/gateway",
    "embeddings-db": "chromadb/embeddings-db",
    "workers": "cloudflare/workers",
    "monitoring": "datadog/monitoring",
    "datahub sdk": "datahub/sdk",
    "deepgram speech": "deepgram/speech",
    "translation": "deepl/translation",
    "headless-cms": "directus/headless-cms",
    "bot": "discord/bot",
    "compressor": "django/compressor",
    "countries": "django/countries",
    "text-to-speech": "elevenlabs/text-to-speech",
    "fastapi-users": "fastapi-users/package",
    "dance": "flask/dance",
    "smorest": "flask/smorest",
    "genai": "gemini/genai",
    "api-gateway": "google/api-gateway",
    "beyondcorp-appconnections": "google/beyondcorp-appconnections",
    "bigquery-datatransfer": "google/bigquery-datatransfer",
    "config-connector": "google/config-connector",
    "deploy": "google/deploy",
    "gke-hub": "google/gke-hub",
    "gke-multicloud": "google/gke-multicloud",
    "managed-identities": "google/managed-identities",
    "network-management": "google/network-management",
    "optimization": "google/optimization",
    "orchestration-airflow": "google/orchestration-airflow",
    "private-ca": "google/private-ca",
    "redis": "google/redis",
    "retail": "google/retail",
    "google speech": "google/speech",
    "tpu": "google/tpu",
    "grpcio": "grpcio/package",
    "httpcore": "httpcore/package",
    "hubspot crm": "hubspot/crm",
    "messaging": "intercom/messaging",
    "issues": "jira/issues",
    "streaming": "kafka/streaming",
    "ade": "landingai/ade",
    "observability": "langfuse/observability",
    "feature-flags": "launchdarkly/feature-flags",
    "litestar": "litestar/package",
    "msal": "msal/package",
    "workspace-api": "notion/workspace-api",
    "okta identity": "okta/identity",
    "chat": "openai/chat",
    "pinecone sdk": "pinecone/sdk",
    "banking": "plaid/banking",
    "orm": "prisma/orm",
    "prometheus-client": "prometheus-client/package",
    "vector-search": "qdrant/vector-search",
    "message-queue": "rabbitmq/message-queue",
    "razorpay payments": "razorpay/payments",
    "key-value": "redis/key-value",
    "rq": "rq/package",
    "salesforce crm": "salesforce/crm",
    "email-api": "sendgrid/email-api",
    "error-tracking": "sentry/error-tracking",
    "sqlalchemy": "sqlalchemy/package",
    "square payments": "square/payments",
    "auth": "stytch/auth",
    "tavily sdk": "tavily/sdk",
    "weaviate-client": "weaviate-client/package",
    "vector-db": "weaviate/vector-db",
    "support": "zendesk/support",
}

# Nutanix SDK modules: module name → package ID
# Total: 13
NUTANIX_MODULES = {
    "nutanix-aiops": "nutanix/nutanix-aiops",
    "nutanix-clustermgmt": "nutanix/nutanix-clustermgmt",
    "nutanix-datapolicies": "nutanix/nutanix-datapolicies",
    "nutanix-dataprotection": "nutanix/nutanix-dataprotection",
    "nutanix-licensing": "nutanix/nutanix-licensing",
    "nutanix-lifecycle": "nutanix/nutanix-lifecycle",
    "nutanix-microseg": "nutanix/nutanix-microseg",
    "nutanix-monitoring": "nutanix/nutanix-monitoring",
    "nutanix-networking": "nutanix/nutanix-networking",
    "nutanix-prism": "nutanix/nutanix-prism",
    "nutanix-sdk": "nutanix/nutanix-sdk",
    "nutanix-vmm": "nutanix/nutanix-vmm",
    "nutanix-volumes": "nutanix/nutanix-volumes",
}

# Bash/DevOps tools (manual list)
BASH_TOOLS = {
    "ansible": "ansible/package",
    "docker": "docker/package",
    "docker compose": "docker/package",
    "git": "pre-commit/package",
    "redis": "redis/key-value",
}

